Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PrimerVistazoASPNETcore.Model;

namespace PrimerVistazoASPNETcore.Controllers
{
    [Route("api/Producto")]
    [ApiController]
    public class ProductoController : Controller
    {
        private readonly MiDbContext DB;

        public ProductoController(MiDbContext db) {
            DB = db;
        }

        [HttpGet]
        public async Task<IActionResult> GetAll() {
            return Json(new { data = await DB.Producto.ToListAsync()});
        }

        [HttpDelete]
        public async Task<IActionResult> Eliminar(int id)
        {
            var ProductoActual = await DB.Producto.FirstOrDefaultAsync(elem => elem.Id == id);
            if (ProductoActual == null) {
                return Json(new { success = false, mensaje = "Error al intentar eliminar el registro"});
            }
            DB.Producto.Remove(ProductoActual);
            await DB.SaveChangesAsync();
            return Json(new { success = true, mensaje = "Se eliminó el registro" });
        }
    }
}

Pages/EjemploMultiSubmit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PrimerVistazoASPNETcore.Pages
{
    public class EjemploMultiSubmitModel : PageModel
    {
        public void OnGet()
        {

        }
        //Los métodos por post deben tener siempre, en su nombre, el texto "OnPost"
        //lo que le continúa es el nombre distintivo de cada método POST.

        public void OnPostTarea1() { 

        }

        public void OnPostTarea2()
        {

        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PrimerVistazoASPNETcore.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PrimerVistazoASPNETcore.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/ListaDeProductos/CrearProducto.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PrimerVistazoASPNETcore.Model;

namespace PrimerVistazoASPNETcore.Pages.ListaDeProductos
{
    public class CrearProductoModel : PageModel
    {
        private readonly MiDbContext DB;
        [BindProperty]
        public Producto Producto { get; set; }
        public CrearProductoModel(MiDbContext db) {
            DB = db;
        }
        public void OnGet()
        {

        }
        public async Task<IActionResult> OnPost() {
            if (ModelState.IsValid)
            {
                await DB.Producto.AddAsync(Producto);
                await DB.SaveChangesAsync();
                return RedirectToPage("Index");
            }
            else {
                return Page();
            }
        }
    }
}

Pages/ListaDeProductos/EditarProducto.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PrimerVistazoASPNETcore.Model;

namespace PrimerVistazoASPNETcore.Pages.ListaDeProductos
{
    public class EditarProductoModel : PageModel
    {
        private MiDbContext DB;
        [BindProperty]
        public Producto Producto { get; set; }
        public EditarProductoModel(MiDbContext db) {
            DB = db;
        }
        public async Task OnGet(int id)
        {
            Producto = await DB.Producto.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid) {
                var ProductoDesdeLaDB = await DB.Producto.FindAsync(Producto.Id);
                ProductoDesdeLaDB.Nombre = Producto.Nombre;
                ProductoDesdeLaDB.Precio = Producto.Precio;
                await DB.SaveChangesAsync();
                return RedirectToPage("Index");
            }
            return RedirectToPage();
        }
    }
}

Pages/ListaDeProductos/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PrimerVistazoASPNETcore.Model;

namespace PrimerVistazoASPNETcore.Pages.ListaDeProductos
{
    public class IndexModel : PageModel
    {
        private readonly MiDbContext DB;
        public IEnumerable<Producto> Productos { get; set; }
        public IndexModel(MiDbContext db) {
            DB = db;
        }
        public async Task OnGet()
        {
            Productos = await DB.Producto.ToListAsync();
        }

        public async Task<IActionResult> OnPostEliminar(int id)
        {
            var ProductoAeliminar = await DB.Producto.FindAsync(id);
            if (ProductoAeliminar == null)
                return NotFound();
            DB.Producto.Remove(ProductoAeliminar);
            await DB.SaveChangesAsync();
            return RedirectToPage("Index");
        }
        //Con esto ya vimos el CRUD, pues creamos registros,los consultamos, los editamos y eliminamos
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PrimerVistazoASPNETcore.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/EjemploMultiSubmit.cshtml
@page
@model PrimerVistazoASPNETcore.Pages.EjemploMultiSubmitModel
@{
    ViewData["Title"] = "EjemploMultiSubmit";
}

<h1>Ejemplo Multiples Submit</h1>
<form method="post">
    <!-- campos listados varios-->
    <input type="submit" value="Envío #1" asp-page-handler="Tarea1"/>
    <!-- Para diferencia a cada botón submit hay que agregar un tag helper asp-page-handler
        conde se referencia al método post en particualr
        -->

    <input type="submit" value="Envío #2" asp-page-handler="Tarea2"/>
</form>

<!-- más ccntenido-->

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido(s)</h1>
    <p>¡Aprenda sobre <a href="https://docs.microsoft.com/aspnet/core">construcción de aplicacioes web con ASP.NET Core!</a>.</p>
</div>

Pages/ListaDeProductos/CrearProducto.cshtml
@page
@model PrimerVistazoASPNETcore.Pages.ListaDeProductos.CrearProductoModel

<h2 class="text-info">Crear Producto</h2>
<div class="container border">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Producto.Nombre"></label>
            </div>
            <div class="col-6">
                <input asp-for="Producto.Nombre" class="form-control" />
            </div>
            <span asp-validation-for="Producto.Nombre" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Producto.Precio"></label>
            </div>
            <div class="col-6">
                <input asp-for="Producto.Precio" class="form-control" />
            </div>
            <span asp-validation-for="Producto.Precio" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <input type="submit" value="Crear" class="btn btn-primary form-control"/>
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-success form-control text-white">Regresar a lista</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{ 
    <partial name="_ValidationScriptsPartial">
}

Pages/ListaDeProductos/EditarProducto.cshtml
@page
@model PrimerVistazoASPNETcore.Pages.ListaDeProductos.EditarProductoModel

<h2 class="text-info">Editar Producto</h2>
<div class="container border">
    <form method="post">
        <input type="hidden" asp-for="Producto.Id"/>
        <!--si hay un campo que no vamos a editar, lo podemo agregar como hidden-->
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Producto.Nombre"></label>
            </div>
            <div class="col-6">
                <input asp-for="Producto.Nombre" class="form-control" />
            </div>
            <span asp-validation-for="Producto.Nombre" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Producto.Precio"></label>
            </div>
            <div class="col-6">
                <input asp-for="Producto.Precio" class="form-control" />
            </div>
            <span asp-validation-for="Producto.Precio" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <input type="submit" value="Aplicar cambios" class="btn btn-primary form-control" />
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-success form-control text-white">Regresar a lista</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial">
}

Pages/ListaDeProductos/Index.cshtml
@page
@model PrimerVistazoASPNETcore.Pages.ListaDeProductos.IndexModel

    <div class="container row">
        <div class="col-9">
            <h2 class="text-info">Lista de productos</h2>
        </div>
        <div class="col-3">
            <a asp-page="CrearProducto" class="btn btn-info text-white">Crear producto</a>
        </div>

        <div class="col-12 border p-3 mt-3">
            <form method="post">
                @if (Model.Productos.Count() > 0)
                {
                <table>
                    <tr class="table-secondary">
                        <th>
                            <label asp-for="Productos.FirstOrDefault().Nombre"></label>
                        </th>
                        <th>
                            <label asp-for="Productos.FirstOrDefault().Precio"></label>
                        </th>
                        <th>
                            <label>Opciones</label>
                        </th>
                    </tr>
                    @foreach (var prod in Model.Productos)
                    {
                        <tr>
                            <td>@Html.DisplayFor(mod => prod.Nombre)</td>
                        
                            <td>@Html.DisplayFor(mod => prod.Precio)</td>
                            <td>
                                <button asp-page-handler="Eliminar" asp-route-id="@prod.Id" onclick="return confirm('¿Seguro que quieres eliminar el registro?')" class="btn btn-danger btn-sm">Eliminar</button>
                                <a asp-page="EditarProducto" asp-route-id="@prod.Id" class="btn btn-success btn-sm text-white">Editar</a>
                            </td>
                        </tr>
                    }
                </table>
                }
                else {
                    <p>¡No hay ningun producto disponible!</p>
                }
            </form>
        </div>

        <!-- A continuación usamos una tabla más estilizada -->
        <div class="col-12" style="text-align:center">
            <br/>
            <span class="h3 text-info">A continuación usamos una tabla más estilizada</span>
        </div>
        <br/>

        <div class="col-12 border p-3">
            <table id="cargar_miTabla" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <td>Nombre</td>
                        <td>Precio</td>
                        <td>Opciones</td>
                    </tr>
                </thead>
            </table>
        </div>
    </div>


@section scripts{ 
    <script src="~/js/listaDeProductos.js"></script>
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrimerVistazoASPNETcore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">PrimerVistazoASPNETcore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/ListaDeProductos/Index">Productos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PrimerVistazoASPNETcore - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>